deployment:
  tasks:
    # Add Composer path according to cPanel PHP version
    - export PATH=/opt/cpanel/composer/bin:/usr/local/bin:$PATH
    # Put app in maintenance mode during deployment
    - 'php artisan down --secret="deploy-secret" || true'
    # Install dependencies
    - 'php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader'
    # Run database migrations (optional)
    - 'php artisan migrate --force'
    # Clear and cache configs, routes, and views
    - 'php artisan config:cache'
    - 'php artisan route:cache'
    - 'php artisan view:cache'
    # Ensure storage and bootstrap/cache are writable
    - 'chmod -R 775 storage bootstrap/cache'
    # Bring app back up
    - 'php artisan up || true'